jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 21

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and fix
        run: pnpm lint:fix

      - name: Build project
        run: pnpm run build
        env:
          BUILD_BASE: /

      - name: List build directory contents
        run: ls -la build

      - name: Print environment variables
        run: printenv

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest